### ISSUE TITLE
Retrieve file path?

### ISSUE THREAD

**Issue by erwal45** [vormkracht10/laravel-open-graph-image#16]
Hi,

First of all, thank you for this very useful package!
Is it possible to retrieve the image via File Storage? In particular, to be able to use the twitter API with the image generated by laravel-open-graph-image.
It would be necessary to be able to force the generation of the image and then retrieve the image path.

Thanks

**Comment by Baspa** [comment]
Hi @erwal45,

You should be able to retrieve the image using the File Storage. But you have to know the signature that's used. We use the signature from the signed url to determine which file to take. The image is saved in the configured storage disk and path, the default values from the config are: 

```php
return [
    // ...

    // The cache location to use.
    'storage' => [
        'disk' => 'public',
        'path' => 'social/open-graph',
    ],
    
    // ...
];
```

The signature is generated based on the parameters used in the `template.blade.php`. You can take a look at the `LaravelOpenGraphImageController` to see how we get the file from the storage. 

Please let me know if you need any more help.

**Comment by erwal45** [comment]
Thanks for the (quick) reply @Baspa 

I managed to do what I wanted (image retrieval and/or generation) using LaravelOpenGraphImageController

Maybe not the best method, but it works!

My twitter notification:

```
public function toTwitter($offer): TwitterMessage
{
    $image = OpenGraphImage::url([...params...]);
    $image_url = parse_url($image);
    parse_str($image_url['query'], $params);
    $image_signature = $params['signature'];
    $image_controller = new LaravelOpenGraphImageController;

    if( !$image_controller->getStorageFileExists($image_signature) )
    {
        $html = View::make('open-graph-image::template', [...params...])->render();
        $image_controller->saveOpenGraphImage($html, $image_signature);
    }

    $image_path = $image_controller->getStorageFilePath($image_signature);

    $status = '...my custom status...';

    return (new TwitterStatusUpdate($status))->withImage( Storage::disk('public')->get($image_path) );
}
```

**Comment by Baspa** [comment]
@erwal45, by looking at your code I think I know now what you meant to do. You want to generate the image from your backend and pass the image url to your `TwitterStatusUpdate` class, am I correct? So without using the blade template on your webpage (which usually generates the url). 

This looks like something we could make a feature off in the package.

**Comment by erwal45** [comment]
hehe yup, that's exactly what I was trying to explain in my 1st post 😅 sorry I wasn't very clear, but it would indeed be a good feature to implement because currently you have to visit a url for the image to be generated

**Comment by Baspa** [comment]
Sounds like a nice feature, I am gonna take a look at it this week (hopefully later today). I will keep you updated @erwal45!

**Comment by erwal45** [comment]
Thanks @Baspa

**Comment by Baspa** [comment]
Hi @erwal45 

When you update the package to v0.4.0 you should be able to generate the image without using the blade directive as following:

```php
$image = OpenGraphImage::createImageFromParams([
    'title' => 'title',
    'description' => 'description',
]);
```

The output of the method is a string which represents the actual image. Please let me know if this suits your needs.

**Comment by erwal45** [comment]
> Hi @erwal45
> 
> When you update the package to v0.4.0 you should be able to generate the image without using the blade directive as following:
> 
> ```
> $image = OpenGraphImage::createImageFromParams([
>     'title' => 'title',
>     'description' => 'description',
> ]);
> ```
> 
> The output of the method is a string which represents the actual image. Please let me know if this suits your needs.

Wow efficient :) that's perfect, thanks!
