### ISSUE TITLE
Error when accessing generated previews

### ISSUE THREAD

**Issue by abobus-2288** [vormkracht10/laravel-open-graph-image#19]
I have just installed the library according to documentation, but the url in og:image returns laravel error page with this error: 

The command "PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`npm root -g` node '/var/www/html/vendor/spatie/browsershot/src/../bin/browser.cjs' '{"url":"file:\/\/\/tmp\/1418125068-0702841001699025455\/index.html","action":"screenshot","options":{"type":"jpeg","quality":80,"args":["--no-sandbox"],"viewport":{"width":1200,"height":630},"displayHeaderFooter":false}}'" failed. Exit Code: 1(General error) Working directory: /var/www/html/public Output: ================ Error Output: ================ [1m[43m[30m Puppeteer old Headless deprecation warning:[0m[33m In the near future `headless: true` will default to the new Headless mode for Chrome instead of the old Headless implementation. For more information, please see https://developer.chrome.com/articles/new-headless/. Consider opting in early by passing `headless: "new"` to `puppeteer.launch()` If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.[0m Error: Could not find Chrome (ver. 119.0.6045.105). This can occur if either 1. you did not perform an installation before running the script (e.g. `npm install`) or 2. your cache path is incorrectly configured (which is: /home/sail/.cache/puppeteer). For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration. at ChromeLauncher.resolveExecutablePath (/var/www/html/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:298:27) at ChromeLauncher.executablePath (/var/www/html/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:204:25) at ChromeLauncher.computeLaunchArguments (/var/www/html/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:97:37) at async ChromeLauncher.launch (/var/www/html/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28) at async callChrome (/var/www/html/vendor/spatie/browsershot/bin/browser.cjs:92:23)

**Comment by Baspa** [comment]
Thanks for mentioning this issue. I guess it has something to do with the Puppeteer version. Can you tell me which version you've installed? @abobus-2288

**Comment by abobus-2288** [comment]
@Baspa 0.4.0. the puppeteer is 21.5.0

**Comment by Baspa** [comment]
I'm gonna try to take a look at it this weekend. You could try to use a previous version of Puppeteer as temporary fix. @abobus-2288

**Comment by abobus-2288** [comment]
@Baspa it doesn't work eve with 19.0.0 puppeteer. Here's another error: 
`
The command "PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`npm root -g` node '/var/www/html/vendor/spatie/browsershot/src/../bin/browser.cjs' '{"url":"file:\/\/\/tmp\/2083857117-0893450001699113885\/index.html","action":"screenshot","options":{"type":"jpeg","quality":80,"args":["--no-sandbox"],"viewport":{"width":1200,"height":630},"displayHeaderFooter":false}}'" failed. Exit Code: 1(General error) Working directory: /var/www/html/public Output: ================ Error Output: ================ Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1045629). at ChromeLauncher.launch (/var/www/html/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:69:23) at async callChrome (/var/www/html/vendor/spatie/browsershot/bin/browser.cjs:92:23) 
`

**Comment by Baspa** [comment]
I just installed the package in a project of mine with no errors at all. Your error mentions this:

> Run `npm install` to download the correct Chromium revision 

Can you try this please? @abobus-2288

**Comment by abobus-2288** [comment]
@Baspa just ran `npm install chromium`, this didn't solve the problem

**Comment by Baspa** [comment]
@abobus-2288 

So if I'm correct you're running the following package versions:

- Laravel Open Graph Image v0.4.0;
- Puppeteer v21.5.0;

and have this blade component in your `blade` file: `<x-open-graph-image::metatags title="Vormkracht10" subtitle="Slimme websites" />`.

When you visit the url thats generated by this `blade` component you get the error you mentioned first?

**Comment by abobus-2288** [comment]
@Baspa
yep

**Comment by Baspa** [comment]
Is this on a local or production environment? I'm still not able to reproduce it.. @abobus-2288

**Comment by abobus-2288** [comment]
@Baspa it's local

**Comment by Baspa** [comment]
I just followed these steps and still couldn't reproduce the issue:

```bash
$ laravel new fresh-laravel
$ cd fresh-laravel
$ composer require vormkracht10/laravel-open-graph-image
$ npm install puppeteer
$ php artisan open-graph-image:install
$ php artisan vendor:publish --tag="open-graph-image-views"
```

Then I added this blade component to `welcome.blade.php`:

`<x-open-graph-image::metatags title="Vormkracht10" subtitle="Slimme websites" />`

Then I visited `fresh-laravel.test` and checked the page source code. I copied the url generated by the blade component and pasted it in my browser. This resulted in:

![Screenshot 2023-11-08 at 11 36 25](https://github.com/vormkracht10/laravel-open-graph-image/assets/10845460/d8eb5ee0-caaa-4893-b3c3-68cd1af0cec3)

Can you please follow the same steps and tell me if it's still broken? Or please provide me the steps you followed so I can try to reproduce the error. @abobus-2288

**Comment by abobus-2288** [comment]
@Baspa sorry for not answering your question for so long, but after just a week of debugging, i solved it. 
Firstly it was a problem with cache, bcs it installed chromium to the nonexistent directory, when i managed to install it, i encountered new problem with shared libraries, and just installed them with this command:
`sudo apt-get install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils`

**Comment by Baspa** [comment]
Glad you found the solution for the problem! @abobus-2288
